# Generated by Django 2.2.19 on 2023-02-13 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230212_1755'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='descritption',
            new_name='description',
        ),
    ]
