# Generated by Django 2.2.19 on 2023-02-18 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230215_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(error_messages={'max_lenght': 'Название группы не должно превышать 200 символов.', 'unique': 'Группа с таким названием уже существует.'}, help_text='Введите название группы', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
