# Generated by Django 2.2.19 on 2023-02-18 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20230218_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(help_text='Добавьте полное описание группы, чтобы вам было проще найти единомышленников!', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(error_messages={'unique': 'Группа с таким идентификатором уже существует.'}, help_text='Введите идентификатор, который будет частью URL страницы./nДопустимо использование латинских букв, символ тире и нижнее подчёркивание.', unique=True, verbose_name='Уникальный идентификатор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(error_messages={'max_lenght': 'Название группы не должно превышать 200 символов.', 'unique': 'Группа с таким названием уже существует.'}, help_text='Введите название группы.', max_length=200, unique=True, verbose_name='Название'),
        ),
    ]
